### ISSUE TITLE
Configuration Wizard page got errors with java 17

### ISSUE THREAD

**Issue by lijinlongpq** [WrenSecurity/wrenam#146]
Hi, 

I just tried WrenAM 15.0.0-M6 with Java 17 and tomcat 9. And having errors on the configuration wizard page. Even though I added: --add-exports=java.base/java.lang.reflect=ALL-UNNAMED, also same error. 
Guice provision errors: 1) Error injecting constructor, org.jruby.exceptions.RaiseException: 
(NameError) missing class or uppercase package name (`java.lang.reflect.Modifier'), 
caused by Unable to make static boolean java.lang.reflect.Modifier.isSynthetic(int) accessible: 
module java.base does not "opens java.lang.reflect" to unnamed module @65086bd1 at 
org.forgerock.openam.core.rest.docs.api.ApiDocsService.(Unknown Source) 
while locating org.forgerock.openam.core.rest.docs.api.ApiDocsService 
while locating org.forgerock.openam.http.HttpRouterProvider 
at org.forgerock.openam.http.HttpGuiceModule.configure(HttpGuiceModule.java:44) 
while locating org.forgerock.http.Handler annotated with @com.google.inject.name.Named(value=HttpHandler) for parameter 0 at org.forgerock.openam.http.OpenAMHttpApplication.(Unknown Source) at org.forgerock.openam.http.OpenAMHttpApplication.class(Unknown Source) while locating org.forgerock.openam.http.OpenAMHttpApplication while locating org.forgerock.http.HttpApplication 1 error, refer to install.log under /home/user/openam for more information.

**Comment by pavelhoral** [comment]
Try to match your JVM arguments with the ones [defined in Dockerfile](https://github.com/WrenSecurity/wrenam/blob/main/Dockerfile#L42-L49):

```
--add-exports=java.base/sun.security.tools.keytool=ALL-UNNAMED
--add-exports=java.base/sun.security.x509=ALL-UNNAMED
--add-exports=java.management/sun.management=ALL-UNNAMED
--add-exports=java.xml/com.sun.org.apache.xerces.internal.dom=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
--add-opens=java.base/java.util.regex=ALL-UNNAMED
```

**Comment by lijinlongpq** [comment]
thanks,

it works
