### ISSUE TITLE
Do not send SSO cookie as query parameter during login

### ISSUE THREAD

**Issue by pavelhoral** [WrenSecurity/wrenam#169]
XUI sends SSO cookie as a query parameter at the end of the login process to obtain session information:

```
POST /auth/json/sessions?_action=getSessionInfo&tokenId=AQIC5w....
```

This has been reported repeatedly by pentesters. It would be nice if the request could be rewritten to request body. If this is not possible, we need a good reason why.

----

There is a related issue regarding `getSessionInfo` - #109.

**Comment by krausvo1** [comment]
I have just tried and the mentioned request is already a POST request. However the token really is sent in a query parameter.

I have tried to send the token in POST request's body, but it is ignored this way. However I have found out that the token is being read from `iPlanetDirectoryPro` cookie that is being sent with the request. The should always be included, because it is set after predecessor "authenticate" request.
 
So I think the token can actually be dropped from the request altogether.

**Comment by pavelhoral** [comment]
> I've been debugging the problem and I've found that the mentioned request is already a POST request.

This was mistake on my side... I have updated the original report.

I did not realize that the resource is explicitly [checking only the URL](https://github.com/WrenSecurity/wrenam/blob/8447f253f65105554fda6789b160b4fb79478a9b/openam-core-rest/src/main/java/org/forgerock/openam/core/rest/session/SessionResourceV2.java#L269) as the content is `application/json` and no `application/x-www-form-urlencoded` (which obviously makes sense for JSON REST API 🙄).

I will have to look at the UI logic if we can simply drop the query parameter. There might be use-cases when the cookie is different from what the front-end want to check.

Or as an alternative we might add support for something like `{ "tokenId": "..." }` as the request body. But that would require some additional research as well.

**Comment by pavelhoral** [comment]
I have searched through the openam-ui-ria code and it is true that the token is always exclusively [read from the cookie value](https://github.com/WrenSecurity/wrenam/blob/8447f253f65105554fda6789b160b4fb79478a9b/openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/user/login/tokens/SessionToken.jsm#L42) and then passed to other components. The only place where the token can be different is in the [token validator](https://github.com/WrenSecurity/wrenam/blob/8447f253f65105554fda6789b160b4fb79478a9b/openam-ui/openam-ui-ria/src/main/js/config/process/AMConfig.js#L233C12-L233C25) that can have _stale_ cookie value.

I understand why we might want to check consistency between the UI state (e.g. _Signed in as_ information) and the currently active session. For example when user reauthenticates in a different window, that might break UI state in the previously active window.

I am fine with simply removing support for the "tokenId" query parameter in the UI. However we should do it in a way that keeps the code clean.
