### ISSUE TITLE
WrenAM 13.5 build failure due to 'org.restlet.jee' artifacts not being available

### ISSUE THREAD

**Issue by siepkes** [WrenSecurity/wrenam#23]
`org.restlet.jee` Artifacts used to be available in the maven.forgerock.org repo but are no longer publicly availabe:
```
[ERROR] Failed to execute goal on project openam-http-client: Could not resolve dependencies for project org.forgerock.openam:openam-http-client:jar:13.5.1-SNAPSHOT: Failed to collect dependencies at org.restlet.jee:org.restlet:jar:2.3.4: Failed to read artifact descriptor for org.restlet.jee:org.restlet:jar:2.3.4: Could not transfer artifact org.restlet.jee:org.restlet:pom:2.3.4 from/to forgerock-staging-repository (http://maven.forgerock.org/repo/releases): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
```

**Comment by siepkes** [comment]
@Kortanul `org.restlet.jee` is not published on Maven central. It used to be hosted on FR Maven but isn't available anymore. It's only on their own repo ( http://maven.restlet.com/ ). Basically we need (taken from my local repo install script for testing):

```
install_pom "org/restlet/jee/org.restlet.parent/2.3.4/org.restlet.parent-2.3.4.pom"
install_artifact "org/restlet/jee/org.restlet/2.3.4/org.restlet-2.3.4"
install_artifact "org/restlet/jee/org.restlet.ext.json/2.3.4/org.restlet.ext.json-2.3.4"
install_artifact "org/restlet/jee/org.restlet.lib.org.json/2.0/org.restlet.lib.org.json-2.0"
install_artifact "org/restlet/jee/org.restlet.ext.xml/2.3.4/org.restlet.ext.xml-2.3.4"
install_artifact "org/restlet/jee/org.restlet.ext.servlet/2.3.4/org.restlet.ext.servlet-2.3.4"
install_artifact "org/restlet/jee/org.restlet.ext.jackson/2.3.4/org.restlet.ext.jackson-2.3.4"
install_artifact "org/restlet/jee/org.restlet.ext.slf4j/2.3.4/org.restlet.ext.slf4j-2.3.4"
install_artifact "org/restlet/jee/org.restlet.ext.freemarker/2.3.4/org.restlet.ext.freemarker-2.3.4"
```

These can be downloaded from this location: https://restlet.com/open-source/downloads/download/2.3.4/jee/zip/ . However the easiest way to deploy all these is probably to clone the restlet GIT repo ( https://github.com/restlet/restlet-framework-java/tree/2.3.4/modules ) with the 2.3.4 tag and then do a Maven deploy with something like: 

```
 -DaltDeploymentRepository=releases::default::https://maven.foo.com/content/repositories/releases/
```

**Comment by Kortanul** [comment]
On it

**Comment by Kortanul** [comment]
I should just be able to add the Restlet Maven repository to our list of third-party repositories and then JFrog will automatically cache it. I may need to apply a third-party signing key to it since I don't think Restlet signed this version. Let us discover.

**Comment by Kortanul** [comment]
@siepkes As promised, the upstream http://maven.restlet.com/ repo has been added as a remote repo that's aggregated together in our `releases` virtual repo on JFrog. Can you give the build a shot with a clean M2 repo and let me know if it looks all right? I suspect I may need to do some GPG signing.

**Comment by siepkes** [comment]
@Kortanul Nuked my `.m2` and rebuild; Works, thanks! Can you fix the signing of the `2.3.4` JEE artifacts? Like you said signing info is already present for the `2.1.2` OSGi artifacts.

**Comment by Kortanul** [comment]
@siepkes just to verify -- you had to build it with `-Dignore-artifact-sigs`?

**Comment by siepkes** [comment]
Closing this since 13.5 is build-able hence this is no longer an issue.
