### ISSUE TITLE
WrenAM 13.5 build failure due to 'jaxrpc' artifact not being available 

### ISSUE THREAD

**Issue by siepkes** [WrenSecurity/wrenam#27]
Wren:AM 13.5 currently has a dependency on JAX-RPC 1.1.3_01-041406. The full name of the artifact is `external:jaxrpc-impl:jar:1.1.3_01-041406`. Judging from the `external` group name this appears to be a FR special release of the artifact. The `041406` is a tag in the [JAX-RPC repo](https://github.com/javaee/jax-rpc-ri/tree/JAXRPC_1_1_3_01_PKG_041406).

Wren:AM uses the normal corresponding API module (`javax.xml:jaxrpc-api`). It seems only the `external:jaxrpc-impl:jar:1.1.3_01-041406` artifact needs to be deployed.

**Comment by siepkes** [comment]
@Kortanul Could you please upload and sign this artifact: https://github.com/WrenSecurity/wrensec-deps/tree/master/repo/external/jaxrpc-impl/1.1.3_01-041406 ?

**Comment by siepkes** [comment]
@Kortanul Your right, sorry for the noise. This was due to a mix up of proxy settings and Maven `~/.m2/settings.xml` conspiring against me ;-).

**Comment by Kortanul** [comment]
thank goodness!
