### ISSUE TITLE
Creating custom authentication module with default name via ssoadm breaks XUI

### ISSUE THREAD

**Issue by pavelhoral** [WrenSecurity/wrenam#32]
When creating custom authentication module with the [same name as the module name](https://github.com/WrenSecurity/wrenam/blob/master/openam-core/src/main/java/com/sun/identity/authentication/config/AMAuthenticationManager.java#L712) via *ssoadm*, the configuration is stored in organization's default service entry.

However when XUI makes request for module instance configuration, it always goes for subschema configuration (unless the module [is from a predefined set](https://github.com/WrenSecurity/wrenam/blob/master/openam-core-rest/src/main/java/org/forgerock/openam/core/rest/sms/SmsResourceProvider.java#L263) of [auto-created modules](https://github.com/WrenSecurity/wrenam/blob/master/openam-core-rest/src/main/java/org/forgerock/openam/core/rest/sms/SmsResourceProvider.java#L114))

When creating custom module instance from XUI, it [automatically creates subschema config](https://github.com/WrenSecurity/wrenam/blob/master/openam-core-rest/src/main/java/org/forgerock/openam/core/rest/sms/SmsCollectionProvider.java#L233) that inherits organization configuration. So XUI is consistent in this sense and the issue is probably in ssoadm.

FR references: 

* https://bugster.forgerock.org/jira/browse/OPENAM-6676
* https://bugster.forgerock.org/jira/browse/OPENAM-9993

**Comment by pavelhoral** [comment]
Support for the same name of instance as the module type was added in a8e92a7. Seems like this commit forgot to modify `AMAuthenticationManager`'s `createInstance` and `deleteInstance` methods.

**Comment by pavelhoral** [comment]
Also REST endpoint is never properly cleaning up service entry after deleting the last instance. And there is another more severe issue in REST -> when deleting instance with the default name, it deletes the whole service with all it's instances :/

**Comment by karelmaxa** [comment]
Fixed in https://github.com/WrenSecurity/wrenam/pull/84.
