### ISSUE TITLE
Some menu not work

### ISSUE THREAD

**Issue by epili** [WrenSecurity/wrenam#35]
The version that we want to build and use is wrenam 13.5.x.
After built and deployed the wrenam app, If I try to click on button edit of "REALM"  funciton, the wrenam not show the form.
The problem is on the openam-ui/openam-ui-ria project. 
The pom was modified to switch on new repository, but the main.js file refers the old names. 
Es:   main.js --> "selectize" : "libs/selectize-non-standalone-0.12.1-min" - on the new repository (https://wrensecurity.jfrog.io/wrensecurity/releases/org/forgerock/commons/ui/libs/) the name is selectize.

**Comment by Kortanul** [comment]
@epili Now that #36 has been merged, can you try a new build off of our `sustaining/13.5.x` branch?

**Comment by epili** [comment]
The build works and now the menus are visible.
Many thanks

**Comment by siepkes** [comment]
@epili Good to hear and thanks again for the report!
