### ISSUE TITLE
WrenAM 13.5 Modifying OIDC supported claims and scopes require server restart

### ISSUE THREAD

**Issue by siepkes** [WrenSecurity/wrenam#37]
In order for modifications made to the `Supported Claims` and `Supported Scopes` in an `OAuth2 Provider` (service) to become effective a server restart is required. Other options like the `Enable "claims_parameter_supported"` do become effective immediately without a server restart.

While researching this behavior I discovered this is a know issue in our common ancestor known as [OPENAM-10584](https://bugster.forgerock.org/jira/browse/OPENAM-10584). According to this issue other settings in the `OAuth2 Provider` might (unconfirmed) also exhibit this (unwanted) behavior.

**Comment by karelmaxa** [comment]
Fixed in #101.
