### ISSUE TITLE
LDAP connection leak during policy update

### ISSUE THREAD

**Issue by pavelhoral** [WrenSecurity/wrenam#6]
There is a connection leak here - https://github.com/WrenSecurity/wrenam/blob/sustaining/13.5/openam-core/src/main/java/com/sun/identity/sm/ldap/SMSLdapObject.java#L624

When any component makes invalid search request (e.g. with non-existing base DN), the connection is never closed (returned to the pool). The whole `SMSLdapObject` looks full of similar corner cases, however this one happens quite often when updating policies.

**Comment by pavelhoral** [comment]
Checked the other methods and they are using *try-with-resources*, so the leak is only in the mentioned method.

**Comment by giuffridacarlo** [comment]
hello,
this is OPENAM-9095 issue. The solution is in

- jar: openam-core-13.x.x.jar
- package: com.sun.identity.sm.ldap
- class: SMSLdapObject

replace
----- STAR CODE
Connection conn = getConnection(adminPrincipal);
ConnectionEntryReader results = searchObjectsEx(token, startDN, filter,
    numOfEntries, timeLimit, sortResults, ascendingOrder, conn);
return new SearchResultIterator(results, excludes, conn);
------ END CODE
with something like

---- START CODE
try (Connection conn = getConnection(adminPrincipal)){
    ConnectionEntryReader results = searchObjectsEx(token, startDN, filter,
      numOfEntries, timeLimit, sortResults, ascendingOrder, conn);
  return new SearchResultIterator(results, excludes, conn);
}
---- END CODE
best regards,
Carlo

2017-11-24 14:50 GMT+01:00 Pavel Horal <notifications@github.com>:

**Comment by pavelhoral** [comment]
I am not sure whether closing the connection on an active iterator is a good idea. Theoretically the connection can still be actively returning search results when this methods returns `ConnectionEntryReader`.

**Comment by siepkes** [comment]
Fixed by #7.
