### ISSUE TITLE
Authentication chain is not updated immediately

### ISSUE THREAD

**Issue by fyrbach** [WrenSecurity/wrenam#74]
Authentication chain update will not take effect until Wren:AM restart.

**Steps to reproduce**:

1. Run clean Wren:AM with default configuration
2. Create new authentication chain (e.g. "demo") in top level realm
3. Add modules "Data Store" and "HOTP" into that chain
4. Try login using this chain (http://.../auth?service=demo)
    * An user "demo" with password "changeit" can be used
    * User has to pass both auth. modules
5. Remove "HOTP" module from auth. chain
6. Try login using the chain again
    * User still has to pass both auth. modules

**Expected behavior**:

Changes in authentication chain will take effect immediately after save.

**Comment by fyrbach** [comment]
This issue is caused by wrensecurity/wrends#69.

**Comment by pavelhoral** [comment]
I was not able to replicate the issue with the current version with upgraded Wren:DS dependency.
