### ISSUE TITLE
Failed to build openam post authentication plugin.

### ISSUE THREAD

**Issue by diedel** [WrenSecurity/wrenam#8]
Trying to build the Post Authentication plugin sample from ForgeRock (https://github.com/ForgeRock/openam-post-auth-sample) I receive this error:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.404 s
[INFO] Finished at: 2018-01-11T19:10:56+01:00
[INFO] Final Memory: 15M/46M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project openam-post-auth-sample: Could not resolve dependencies for project org.forgerock.openam.examples:openam-post-auth-sample:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at org.forgerock.openam:openam-core:jar:13.5.0-SNAPSHOT -> org.forgerock.commons:forgerock-bloomfilter-core:jar:1.0.1 -> org.forgerock.commons:forgerock-util:jar:3.0.1: Failed to read artifact descriptor for org.forgerock.commons:forgerock-util:jar:3.0.1: Could not transfer artifact org.forgerock.commons:forgerock-util:pom:3.0.1 from/to forgerock-private-releases (https://maven.forgerock.org/repo/private-releases): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

I noticed that I have in my .m2 repository the org.forgerock.commons:forgerock-util:jar:3.0.2 version, but not the required 3.0.1 version.
I built the main wrenam project successfully so I thought all the dependencies were installed in my local .m2 repository.

What I don't understand is how the org.forgerock.openam:openam-core:jar:13.5.0-SNAPSHOT was built if the  org.forgerock.commons:forgerock-util:jar:3.0.1 was missing.

Maybe I should to instruct Maven to get only the local dependencies?

**Comment by siepkes** [comment]
Haven't looked in-depth yet but this might help; WrenAM 13.5.0-SNAPSHOT is based on the latest OpenAM 13.5 sources we had available at the time; OpenAM 13.5.0 RC11. The ForgeRock final version of OpenAM 13.5 is basically RC17. The ForgeRock samples repo mostly likely assume 13.5.0 final. It could very well be that between RC11 and RC17 the version of some dependencies changed. So you might need to change some versions in the ForgeRock samples POM.

**Comment by diedel** [comment]
After some investigation I think the problem is that Maven search for newer versions of local artifacts in remote repositories, following a daily frequency.

The missing dependency was already in wrensec-deps repository:
https://github.com/WrenSecurity/wrensec-deps/tree/master/repo/org/forgerock/commons/forgerock-util/3.0.1

I have to test and confirm, but I thinks the solution is to load again the wrensec-deps and to build wrenam project. Afterwards to build the post authentication sample, during the same day... :) Or with the -o (offline) option to avoid Maven remote connections.

**Comment by diedel** [comment]
Well... I was partially wrong in my previous comment. Sorry.

The forgerock-util-3.0.1 dependency does exists in wrensec-deps BUT is not installed by the wrenam_13-5 script, it's installed by the wrenam_13 script.
Maybe adding `install_artifact "org/forgerock/commons/forgerock-util/3.0.1/forgerock-util-3.0.1"` will resolve the problem?

**Comment by diedel** [comment]
>  The ForgeRock samples repo mostly likely assume 13.5.0 final

The sample's pom has version 14.0.0 by default, but the build instructions guides you to modify that version accordingly to your OpenAM version, in my case 13.5.0-SNAPSHOT.

**Comment by diedel** [comment]
The only openam dependencies of the sample are the openam-core-13.5.0-SNAPSHOT and openam-shared-13.5.0-SNAPSHOT, which are built during the wrenam main build.

Again, as I pointed out in my first comment, the wrenam build was ok and all the dependencies were resolved (including the forgerock-util dependency). Then why the sample build fails if its starting dependencies are dependencies of wrenam which resolved OK , including the transitive dependencies?

What about the Nearest definition First or Nearest Wins Strategy of Maven to resolve dependencies versions?:
[http://techidiocy.com/maven-dependency-version-conflict-problem-and-resolution/](url)

**Comment by siepkes** [comment]
Thanks for looking in to it!

I do think that for the long(er) term maintaining compatibility with FR sample is not possible for Wren since OpenAM will only drifter further away from wren:AM (I doubt compatibility with Wren is an objective for FR ;-). Therefor I have forked the repo as `wrenam-sample-post-auth` under the WrenSecurity umbrella. Looking forward to any pull requests you might have to get this sample fixed!

Any issues related to the sample can be created in the `wrenam-sample-post-auth` repo. Closing this issue since it is not really related to wren:AM itself.

**Comment by diedel** [comment]
Thanks siepkes.

Just to say that this post authentication plugin sample it's not just any sample. I think it's not the sample by itself but the wrenam/openam plugin functionality what is being tested here. If compatibility cannot be maintained with the sample, at least is expected to have compatibility with the plugin functionality (or a new one).

In my case I have a need the it's covered by the plugin functionality of wrenam/openam, and I have to adapt this sample to that need. Please see: [https://forum.forgerock.com/topic/custom-ldap-attribute/](url)

I'll continue to find a solution, working with the new repo you created. If it's not possible to fix the sample maybe I should think about adapting the corresponding wrenam code.
