### ISSUE TITLE
Update README and add "contributing guidelines" to Wren:AM

### ISSUE THREAD

**Issue by Kortanul** [WrenSecurity/wrenam#9]
we need help getting this project moving even faster. probably the best way to do this is to add contributing guidelines, per:
https://github.com/blog/1184-contributing-guidelines

there are some examples from Filip of Orchitech that need to be reviewed and incorporated: https://github.com/smolafilip/wrensec-website/wiki/Branching

in addition, the build instructions in the README file likely need updating as well.

**Comment by Kortanul** [comment]
@siepkes looks like this is all set. can you confirm?

**Comment by siepkes** [comment]
Regarding the `feature/` branches, don't we have GitHub PR's for those?

**Comment by karelmaxa** [comment]
README in main development branch was completely rewritten.
